In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/sample_data/cars.csv')

In [ ]:
print(df.head())
print(df.dtypes)

          Unnamed: 0   mpg  cyl   disp     hp  drat     wt   qsec  vs  am  \
0          Mazda RX4  21.0    6  160.0  110.0  3.90  2.620  16.46   0   1
1      Mazda RX4 Wag  21.0    6  160.0    NaN  3.90  2.875  17.02   0   1
2         Datsun 710  22.8    4  108.0   93.0  3.85  2.320  18.61   1   1
3     Hornet 4 Drive  21.4    6  258.0  110.0  3.08  3.215  19.44   1   0
4  Hornet Sportabout  18.7    8  360.0  175.0  3.15  3.440  17.02   0   0

   gear  carb
0     4     4
1     4     4
2     4     1
3     3     1
4     3     2
Unnamed: 0     object
mpg           float64
cyl             int64
disp          float64
hp            float64
drat          float64
wt            float64
qsec          float64
vs              int64
am              int64
gear            int64
carb            int64
dtype: object

In [ ]:
df['hp'].fillna(df['hp'].mean(), inplace=True)
df.dropna(subset=['hp'], inplace=True) # Eliminar filas.

In [ ]:
df_filtered = df[df['cyl'] == 6]
print(df_filtered)

        Unnamed: 0   mpg  cyl   disp          hp  drat     wt   qsec  vs  am  \
0        Mazda RX4  21.0    6  160.0  110.000000  3.90  2.620  16.46   0   1
1    Mazda RX4 Wag  21.0    6  160.0  151.074074  3.90  2.875  17.02   0   1
3   Hornet 4 Drive  21.4    6  258.0  110.000000  3.08  3.215  19.44   1   0
5          Valiant  18.1    6  225.0  105.000000  2.76  3.460  20.22   1   0
9         Merc 280  19.2    6  167.6  123.000000  3.92  3.440  18.30   1   0
10       Merc 280C  17.8    6  167.6  123.000000  3.92  3.440  18.90   1   0
29    Ferrari Dino  19.7    6  145.0  175.000000  3.62  2.770  15.50   0   1

    gear  carb
0      4     4
1      4     4
3      3     1
5      3     1
9      4     4
10     4     4
29     5     6

In [ ]:
def categorize_hp(hp):
if hp > 150:
return 'High'
elif hp > 80:
return 'Medium'
else:
return 'Low'
df_filtered['HP_Category'] = df_filtered['hp'].apply(categorize_hp)

IndentationError: expected an indented block after function definition on line 1 (<ipython-input-14-43833bd018b6>, line 2)

In [ ]:
df_filtered.to_csv('.\dataset\cleaned_cars_dataset.csv', index=False)

In [ ]:
print("DataFrame is saved as 'cleaned_cars_dataset.csv'.")

DataFrame is saved as 'cleaned_cars_dataset.csv'.